language: java
sudo: required
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh xocl releng/edu.kit.ipd.sdq.xocl.updatesite.aggregated final kit-sdq updatesite

notifications:
  slack:
    secure: eNI1vUWfvf8DwuMAHtcQ8suSV/frjjZQTFGgvXG1ZH5W9PQrzflQJ3A219c6XlzRhyjhB9U8K/ELGDyAsSGUHIFJy4O1P9WgqEFB/mFSLrzlFQ49BlZemvjbQ5CjIAM70NvpwD7uDBF8XVvN98KBc6BXHlJi71tv1wzdl8vrJRknnYdqwlChg9PRo63xNAYuFm/TiUTeX5fh0DFCC7GtpPoBMDKvrviWVzsm847vSKx9dEF8I7MAxyouA5bP8E62zohF/oJOpZliXVahkkrWVUqWPkEGS1+51KfvMVZRDETnwGdneG6jCOi80zki4f1JVJETNtGXp6nLFdnzjw5ZANxoTe4z5//0RC7odsTIhtOIWkyYbxRWLnI9G0ZEE9gx6cflZ7DJuYZYElzOuUw/l262yQOa3HbDAahxy/rNMiMVHcYiwF4/V0SB3aiIrgsGm1zIwKDHA4mDyk3GEalUn7D4He96FshKtDBA0iYVipP2dclScz2NT6AA0INo0veKiz3ZvGooVWypruO+1AxKiBX4rL0rUrFvQ/HjAmABkUn7Ao75SKP/TUMcGkUtrz0NrAeDm1DZIDHv8lIrat+4e2TL5O8aM/YAJErve2ER28mKF4HWOBofxndZsZaSMp83eWw5zNnz6bUWVKU8x51WEzrdrXHdavpqdEFtWMYk5rg=